In [1]:
import json2vec as rf 
from relbench.datasets import get_dataset
dataset = get_dataset("rel-f1")

/Users/reid/py/benchmarks/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Downloading file 'rel-f1/db.zip' from 'https://relbench.stanford.edu/download/rel-f1/db.zip' to '/Users/reid/Library/Caches/relbench'.
100%|███████████████████████████████████████| 704k/704k [00:00<00:00, 1.20GB/s]
Unzipping contents of '/Users/reid/Library/Caches/relbench/rel-f1/db.zip' to '/Users/reid/Library/Caches/relbench/rel-f1/.'

In [2]:
db = dataset.get_db()

table_names = []

for table_name, table in db.table_dict.items():
    table_names.append(table_name)
    print(f"\n=== {table_name} ===")
    print(table.df.head())

Loading Database object from /Users/reid/Library/Caches/relbench/rel-f1/db...
Done in 0.16 seconds.

=== qualifying ===
   qualifyId  raceId  driverId  constructorId  number  position       date
0          0     548        43             26      26        19 1994-03-26
1          1     548       100             30      31        26 1994-03-26
2          2     548        91             29      34        25 1994-03-26
3          3     548        82             31      11        24 1994-03-26
4          4     548       105             32      19        23 1994-03-26

=== drivers ===
   driverId   driverRef code  forename     surname        dob nationality
0         0    hamilton  HAM     Lewis    Hamilton 1985-01-07     British
1         1    heidfeld  HEI      Nick    Heidfeld 1977-05-10      German
2         2     rosberg  ROS      Nico     Rosberg 1985-06-27      German
3         3      alonso  ALO  Fernando      Alonso 1981-07-29     Spanish
4         4  kovalainen  KOV    Heikki  Kovalainen 1981-10-19     Finnish

=== results ===
   resultId  raceId  driverId  constructorId  number  grid  position  \
0         0       0       660            152    18.0    21      11.0
1         1       0       790            149     8.0    12       NaN
2         2       0       579             49     1.0     3       NaN
3         3       0       661            149     9.0    10       NaN
4         4       0       789            152    17.0     7       NaN

   positionOrder  points  laps  milliseconds  fastestLap  rank  statusId  \
0             11     0.0    64           NaN         NaN   NaN        16
1             21     0.0     2           NaN         NaN   NaN       126
2             12     0.0    62           NaN         NaN   NaN        44
3             20     0.0     5           NaN         NaN   NaN         6
4             19     0.0     8           NaN         NaN   NaN        51

        date
0 1950-05-13
1 1950-05-13
2 1950-05-13
3 1950-05-13
4 1950-05-13

=== standings ===
   driverStandingsId  raceId  driverId  points  position  wins       date
0                  0       0       789     0.0        20     0 1950-05-13
1                  1       0       640     0.0        18     0 1950-05-13
2                  2       0       589     0.0        19     0 1950-05-13
3                  3       0       669     0.0        15     0 1950-05-13
4                  4       0       661     0.0        22     0 1950-05-13

=== races ===
   raceId  year  round  circuitId                name       date      time
0       0  1950      1          8  British Grand Prix 1950-05-13  00:00:00
1       1  1950      2          5   Monaco Grand Prix 1950-05-21  00:00:00
2       2  1950      3         18    Indianapolis 500 1950-05-30  00:00:00
3       3  1950      4         65    Swiss Grand Prix 1950-06-04  00:00:00
4       4  1950      5         12  Belgian Grand Prix 1950-06-18  00:00:00

=== constructors ===
   constructorId constructorRef        name nationality
0              0        mclaren     McLaren     British
1              1     bmw_sauber  BMW Sauber      German
2              2       williams    Williams     British
3              3        renault     Renault      French
4              4     toro_rosso  Toro Rosso     Italian

=== constructor_results ===
   constructorResultsId  raceId  constructorId  points       date
0                     0      48            103    13.0 1956-01-22
1                     1      48              5    12.0 1956-01-22
2                     2      54            126     0.0 1956-08-05
3                     3      54            103    15.0 1956-08-05
4                     4      54              5     9.0 1956-08-05

=== circuits ===
   circuitId   circuitRef                            name      location  \
0          0  albert_park  Albert Park Grand Prix Circuit     Melbourne
1          1       sepang    Sepang International Circuit  Kuala Lumpur
2          2      bahrain   Bahrain International Circuit        Sakhir
3          3    catalunya  Circuit de Barcelona-Catalunya      Montmeló
4          4     istanbul                   Istanbul Park      Istanbul

     country       lat        lng    alt
0  Australia -37.84970  144.96800   10.0
1   Malaysia   2.76083  101.73800   18.0
2    Bahrain  26.03250   50.51060    7.0
3      Spain  41.57000    2.26111  109.0
4     Turkey  40.95170   29.40500  130.0

=== constructor_standings ===
   constructorStandingsId  raceId  constructorId  points  position  wins  \
0                       0      64            103     3.0         3     0
1                       1      64              5     6.0         2     0
2                       2      64             85     8.0         1     1
3                       3      65             85    16.0         1     2
4                       4      65             31     0.0         5     0

        date
0 1958-01-19
1 1958-01-19
2 1958-01-19
3 1958-05-18
4 1958-05-18

In [3]:
table_names

['qualifying',
 'drivers',
 'results',
 'standings',
 'races',
 'constructors',
 'constructor_results',
 'circuits',
 'constructor_standings']

# Qualifying

In [5]:
db.table_dict["qualifying"].df.head()

   qualifyId  raceId  driverId  constructorId  number  position       date
0          0     548        43             26      26        19 1994-03-26
1          1     548       100             30      31        26 1994-03-26
2          2     548        91             29      34        25 1994-03-26
3          3     548        82             31      11        24 1994-03-26
4          4     548       105             32      19        23 1994-03-26

# Drivers

In [6]:
db.table_dict["drivers"].df.head()

   driverId   driverRef code  forename     surname        dob nationality
0         0    hamilton  HAM     Lewis    Hamilton 1985-01-07     British
1         1    heidfeld  HEI      Nick    Heidfeld 1977-05-10      German
2         2     rosberg  ROS      Nico     Rosberg 1985-06-27      German
3         3      alonso  ALO  Fernando      Alonso 1981-07-29     Spanish
4         4  kovalainen  KOV    Heikki  Kovalainen 1981-10-19     Finnish

# Results

In [7]:
db.table_dict["results"].df.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionOrder,points,laps,milliseconds,fastestLap,rank,statusId,date
0,0,0,660,152,18.0,21,11.0,11,0.0,64,NaN,NaN,NaN,16,1950-05-13
1,1,0,790,149,8.0,12,NaN,21,0.0,2,NaN,NaN,NaN,126,1950-05-13
2,2,0,579,49,1.0,3,NaN,12,0.0,62,NaN,NaN,NaN,44,1950-05-13
3,3,0,661,149,9.0,10,NaN,20,0.0,5,NaN,NaN,NaN,6,1950-05-13
4,4,0,789,152,17.0,7,NaN,19,0.0,8,NaN,NaN,NaN,51,1950-05-13

# Standings

In [8]:
db.table_dict["standings"].df.head()

   driverStandingsId  raceId  driverId  points  position  wins       date
0                  0       0       789     0.0        20     0 1950-05-13
1                  1       0       640     0.0        18     0 1950-05-13
2                  2       0       589     0.0        19     0 1950-05-13
3                  3       0       669     0.0        15     0 1950-05-13
4                  4       0       661     0.0        22     0 1950-05-13

In [23]:
db.table_dict["standings"].df.sort_values("wins")

       driverStandingsId  raceId  driverId  points  position  wins       date
0                      0       0       789     0.0        20     0 1950-05-13
18120              18120     433       144     0.0        29     0 1986-09-21
18119              18119     433       109     0.0        30     0 1986-09-21
18118              18118     433       159     0.0        26     0 1986-09-21
18117              18117     433       176    22.0         5     0 1986-09-21
...                  ...     ...       ...     ...       ...   ...        ...
25978              25978     726        29   128.0         1    12 2004-08-29
26001              26001     727        29   136.0         1    12 2004-09-12
26033              26033     728        29   136.0         1    12 2004-09-26
26073              26073     730        29   148.0         1    13 2004-10-24
26049              26049     729        29   146.0         1    13 2004-10-10

[28115 rows x 7 columns]

# Races

In [9]:
db.table_dict["races"].df.head()

   raceId  year  round  circuitId                name       date      time
0       0  1950      1          8  British Grand Prix 1950-05-13  00:00:00
1       1  1950      2          5   Monaco Grand Prix 1950-05-21  00:00:00
2       2  1950      3         18    Indianapolis 500 1950-05-30  00:00:00
3       3  1950      4         65    Swiss Grand Prix 1950-06-04  00:00:00
4       4  1950      5         12  Belgian Grand Prix 1950-06-18  00:00:00

In [22]:
db.table_dict["races"].df.count()

raceId       820
year         820
round        820
circuitId    820
name         820
date         820
time         820
dtype: int64

In [21]:
db.table_dict["races"].df.time.replace('00:00:00',None).count()

np.int64(89)

# Constructors

In [ ]:
db.table_dict["constructors"].df.head()

   constructorId constructorRef        name nationality
0              0        mclaren     McLaren     British
1              1     bmw_sauber  BMW Sauber      German
2              2       williams    Williams     British
3              3        renault     Renault      French
4              4     toro_rosso  Toro Rosso     Italian

# Constructor Results

In [11]:
db.table_dict["constructor_results"].df.head()

   constructorResultsId  raceId  constructorId  points       date
0                     0      48            103    13.0 1956-01-22
1                     1      48              5    12.0 1956-01-22
2                     2      54            126     0.0 1956-08-05
3                     3      54            103    15.0 1956-08-05
4                     4      54              5     9.0 1956-08-05

# Circuits

In [12]:
db.table_dict["circuits"].df.head()

,circuitId,circuitRef,name,location,country,lat,lng,alt
0,0,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10.0
1,1,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18.0
2,2,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7.0
3,3,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109.0
4,4,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130.0

In [14]:
db.table_dict["circuits"].df.count()

circuitId     77
circuitRef    77
name          77
location      77
country       77
lat           77
lng           77
alt           74
dtype: int64

In [16]:
db.table_dict["circuits"].df.describe()

       circuitId        lat         lng          alt
count       77.0  77.000000   77.000000    74.000000
mean        38.0  33.442925    1.076683   248.189189
std    22.371857  22.808866   65.516951   365.041851
min          0.0 -37.849700 -118.189000    -7.000000
25%         19.0  32.777400   -9.394170    19.250000
50%         38.0  40.951700    3.930830   129.500000
75%         57.0  46.958900   19.248600   315.500000
max         76.0  57.265300  144.968000  2227.000000

# Constructor Standings

In [13]:
db.table_dict["constructor_standings"].df.head()

,constructorStandingsId,raceId,constructorId,points,position,wins,date
0,0,64,103,3.0,3,0,1958-01-19
1,1,64,5,6.0,2,0,1958-01-19
2,2,64,85,8.0,1,1,1958-01-19
3,3,65,85,16.0,1,2,1958-05-18
4,4,65,31,0.0,5,0,1958-05-18